build:
    environment:
        php:
            version: 8.1
    tests:
        override:
            - true

checks:
    php:
        code_rating: true
        duplication: true

filter:
    paths: [ "src/main/php/*" ]

tools:
    external_code_coverage: true
