linters:
  phpcs:
    standard: './phpcs.xml.dist'
    extensions: '.php'
    exclude:
      - 'Squiz.Classes.ValidClassName'
      - 'PEAR.NamingConventions.ValidClassName'
    tab_width: 4
    ignore: 'src/test/resources/*'
branches:
    ignore: ['1.5.x']
