<?php

use Route24975295 as Route;

class Bootstrap extends Bootstrap24975295
{
    protected function initRouter()
    {
        $this->bootstrap('frontController');
        $front = $this->getResource('frontController');
        $router = $front->getRouter();

        $route = new Hostname24975295('foo', array('module' => 'default' ));
        $router
            ->addRoute('default', $route->chain(new Route('x', array('controller' => 'index'))))
            ->addRoute('default', $route->chain(new Route('x', array('controller' => 'index'))))
            ->addRoute('default', $route->chain(new Route('x', array('controller' => 'index'))))
            ->addRoute('default', $route->chain(new Route('x', array('controller' => 'index'))))
            ->addRoute('default', $route->chain(new Route('x', array('controller' => 'index'))))
            ->addRoute('default', $route->chain(new Route('x', array('controller' => 'index'))))
            ->addRoute('default', $route->chain(new Route('x', array('controller' => 'index'))))
            ->addRoute('default', $route->chain(new Route('x', array('controller' => 'index'))))
            ->addRoute('default', $route->chain(new Route('x', array('controller' => 'index'))))
            ->addRoute('default', $route->chain(new Route('x', array('controller' => 'index'))))
            ->addRoute('default', $route->chain(new Route('x', array('controller' => 'index'))))
            ->addRoute('default', $route->chain(new Route('x', array('controller' => 'index'))))
            ->addRoute('default', $route->chain(new Route('x', array('controller' => 'index'))))
            ->addRoute('default', $route->chain(new Route('x', array('controller' => 'index'))))
            ->addRoute('default', $route->chain(new Route('x', array('controller' => 'index'))))
            ->addRoute('default', $route->chain(new Route('x', array('controller' => 'index'))))
            ->addRoute('default', $route->chain(new Route('x', array('controller' => 'index'))))
            ->addRoute('default', $route->chain(new Route('x', array('controller' => 'index'))))
            ->addRoute('default', $route->chain(new Route('x', array('controller' => 'index'))))
            ->addRoute('default', $route->chain(new Route('x', array('controller' => 'index'))))
            ->addRoute('default', $route->chain(new Route('x', array('controller' => 'index'))))
            ->addRoute('default', $route->chain(new Route('x', array('controller' => 'index'))))
            ->addRoute('default', $route->chain(new Route('x', array('controller' => 'index'))))
            ->addRoute('default', $route->chain(new Route('x', array('controller' => 'index'))))
            ->addRoute('default', $route->chain(new Route('x', array('controller' => 'index'))))
            ->addRoute('default', $route->chain(new Route('x', array('controller' => 'index'))))
            ->addRoute('default', $route->chain(new Route('x', array('controller' => 'index'))))
            ->addRoute('default', $route->chain(new Route('x', array('controller' => 'index'))))
            ->addRoute('default', $route->chain(new Route('x', array('controller' => 'index'))))
            ->addRoute('default', $route->chain(new Route('x', array('controller' => 'index'))))
            ->addRoute('default', $route->chain(new Route('x', array('controller' => 'index'))))
            ->addRoute('default', $route->chain(new Route('x', array('controller' => 'index'))))
            ->addRoute('default', $route->chain(new Route('x', array('controller' => 'index'))))
            ->addRoute('default', $route->chain(new Route('x', array('controller' => 'index'))))
            ->addRoute('default', $route->chain(new Route('x', array('controller' => 'index'))))
            ->addRoute('default', $route->chain(new Route('x', array('controller' => 'index'))))
            ->addRoute('default', $route->chain(new Route('x', array('controller' => 'index'))))
            ->addRoute('default', $route->chain(new Route('x', array('controller' => 'index'))))
            ->addRoute('default', $route->chain(new Route('x', array('controller' => 'index'))))
            ->addRoute('default', $route->chain(new Route('x', array('controller' => 'index'))))
            ->addRoute('default', $route->chain(new Route('x', array('controller' => 'index'))))
            ->addRoute('default', $route->chain(new Route('x', array('controller' => 'index'))))
            ->addRoute('default', $route->chain(new Route('x', array('controller' => 'index'))))
            ->addRoute('default', $route->chain(new Route('x', array('controller' => 'index'))))
            ->addRoute('default', $route->chain(new Route('x', array('controller' => 'index'))))
            ->addRoute('default', $route->chain(new Route('x', array('controller' => 'index'))))
            ->addRoute('default', $route->chain(new Route('x', array('controller' => 'index'))))
            ->addRoute('default', $route->chain(new Route('x', array('controller' => 'index'))))
            ->addRoute('default', $route->chain(new Route('x', array('controller' => 'index'))))
            ->addRoute('default', $route->chain(new Route('x', array('controller' => 'index'))))
            ->addRoute('default', $route->chain(new Route('x', array('controller' => 'index'))))
            ->addRoute('default', $route->chain(new Route('x', array('controller' => 'index'))))
            ->addRoute('default', $route->chain(new Route('x', array('controller' => 'index'))))
            ->addRoute('default', $route->chain(new Route('x', array('controller' => 'index'))))
            ->addRoute('default', $route->chain(new Route('x', array('controller' => 'index'))))
            ->addRoute('default', $route->chain(new Route('x', array('controller' => 'index'))))
            ->addRoute('default', $route->chain(new Route('x', array('controller' => 'index'))))
            ->addRoute('default', $route->chain(new Route('x', array('controller' => 'index'))))
            ->addRoute('default', $route->chain(new Route('x', array('controller' => 'index'))))
            ->addRoute('default', $route->chain(new Route('x', array('controller' => 'index'))))
            ->addRoute('default', $route->chain(new Route('x', array('controller' => 'index'))))
            ->addRoute('default', $route->chain(new Route('x', array('controller' => 'index'))))
            ->addRoute('default', $route->chain(new Route('x', array('controller' => 'index'))))
            ->addRoute('default', $route->chain(new Route('x', array('controller' => 'index'))))
            ->addRoute('default', $route->chain(new Route('x', array('controller' => 'index'))))
            ->addRoute('default', $route->chain(new Route('x', array('controller' => 'index'))))
            ->addRoute('default', $route->chain(new Route('x', array('controller' => 'index'))))
            ->addRoute('default', $route->chain(new Route('x', array('controller' => 'index'))))
        ;
    }
}
