name: PHPStan

on:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - "*"

jobs:
  tests:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    env:
      COMPOSER_NO_INTERACTION: 1

    strategy:
      fail-fast: false
      matrix:
        php: [ '7.4' ]
        setup: [ 'stable' ]
        phpstan: [1.10.25]

    name: PHP ${{ matrix.php }} - ${{ matrix.setup }} - ${{ matrix.phpstan }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          coverage: none
          tools: composer:v2

      - name: Cache Composer packages
        id: composer-cache
        uses: actions/cache@v3
        with:
          path: vendor
          key: ${{ runner.os }}-php-${{ matrix.php }}-${{ matrix.dependency-version }}-${{ hashFiles('**/composer.json') }}
          restore-keys: |
            ${{ runner.os }}-php-${{ matrix.php }}-${{ matrix.dependency-version }}

      - name: Install dependencies
        run: |
          composer require phpstan/phpstan:${{ matrix.phpstan }} --no-interaction --dev --no-update;
          composer update --prefer-dist --no-progress --no-suggest --prefer-${{ matrix.setup }};

      - name: Run PHPStan
        run: vendor/bin/phpstan analyze
